name: test_Django
on: [pull_request, push] # activates the workflow when there is a push or pull request in the repo
jobs:
  test_project:
    runs-on: ubuntu-latest # operating system your code will run on
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install -r requirements.txt # install all our dependencies for the project
      - run: pytest . # run pytest test
  deploy:
    needs: test_project
    name: Deploy to server
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY}}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: "app/"
          EXCLUDE: ""
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: root
          TARGET: '/root/Contacts'
          SCRIPT_AFTER: |
            whoami
            ls -al Contacts
            echo $RSYNC_STDOUT

